
CREATE TABLE ALUNOS (
    ID                  NUMBER(10) NOT NULL,
    NOME                VARCHAR2(100) ,
    EMAIL               VARCHAR2(150),
    DATA_NASCIMENTO     DATE NOT NULL,
    ATIVO               NUMBER(1) DEFAULT 1 NOT NULL,
    CURSO               VARCHAR2(100),
    TURMA               VARCHAR2(50),
    TURNO               VARCHAR2(20),
    DATA_CADASTRO       TIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP,
    USUARIO_CADASTRO    VARCHAR2(50),
    USUARIO_ATUALIZACAO VARCHAR2(50),

    CONSTRAINT PK_ALUNOS PRIMARY KEY (ID)
);


CREATE SEQUENCE SEQ_ALUNOS_ID START WITH 1;


CREATE OR REPLACE TRIGGER TRG_ALUNOS_ID
    BEFORE INSERT ON ALUNOS
    FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_ALUNOS_ID.NEXTVAL;
END;



select * from alunos;
